### ISSUE TITLE
ambiguous wording in the "Ruby Data Types" module

### ISSUE THREAD

**Issue by lqf2b8** [learn-co-curriculum/data-types-readme#11]
Under the "OPERATING ON INTEGERS" section of the "Ruby Data Types" module the three examples methods given are for floats not integers.

Obviously not a big issue as I am sure everyone is still able to follow along but just in case there are any drama majors taking the course you might want to change the wording.

**Comment by AnnJohn** [comment]
@SophieDeBenedetto due by 8/21
