### ISSUE TITLE
The "Edit" function is failing

### ISSUE THREAD

**Issue by anthonyhatala** [learn-co-curriculum/data-types-readme#13]
The "Edit" function is failing when I try to submit a grammatical correction for the lesson.

![screen shot 2015-08-29 at 12 00 37 pm](https://cloud.githubusercontent.com/assets/8661665/9562835/9dcb15de-4e45-11e5-99cd-52ee6c57e914.png)

**Comment by AnnJohn** [comment]
@anthonyhatala Thanks for raising this issue. This looks like it might have been a temporary bug on our end; could you try again and let me know if the submission goes through? Thanks!

**Comment by AnnJohn** [comment]
Closing this issue
