### ISSUE TITLE
"IRB" not previously defined

### ISSUE THREAD

**Issue by markedwardmurray** [learn-co-curriculum/data-types-readme#7]
"IRB" not previously defined : The headline on the next lesson tells me IRB means Interactive Ruby Shell. But I still have no idea what that is.

**Comment by markedwardmurray** [comment]
@SophieDeBenedetto

**Comment by SophieDeBenedetto** [comment]
good catch! I updated the IRB readme to talk about what a REPL is, why we use irb, etc. and moved it to just prior to this data types readme.
